quarkus.datasource.db-kind=${db_kind}
quarkus.datasource.username=${username}
quarkus.datasource.password=${password}
quarkus.datasource.jdbc.url=${jdbc_url}
quarkus.http.cors.enabled=${cors_enabled}
quarkus.http.cors.origins=${cors_origins}
quarkus.http.cors.methods=${cors_methods}
quarkus.http.cors.headers=${cors_headers}
quarkus.http.cors.access-control-allow-credentials=${allow_credentials}
api_env=${api_env}
domain=${domain}