DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users (
    id VARCHAR(255) PRIMARY KEY UNIQUE,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
    );

DROP TABLE IF EXISTS sessions;
CREATE TABLE IF NOT EXISTS sessions (
    id VARCHAR(255) PRIMARY KEY UNIQUE,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires TIMESTAMP NOT NULL,
    user_id VARCHAR(255) REFERENCES users(id)
);